name: Commit lint

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    needs:
      - pre_run
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4
